# Use the official Node.js image as the base image
FROM node:20.10.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock to the container
COPY package*.json .

COPY . .

# Install project dependencies
RUN yarn install

EXPOSE 3000

# Start the Next.js app
CMD ["yarn" , "dev"]

